[package]
name = "parser"
version = "0.1.0"
edition = "2024"


[dependencies]
parser_derive = { path = "./parser_derive" }
tokio = {version = "1.0", features = ["full"]}
log = "0.4.27"
simple_logger = "5.0.0"
futures = "0.3.31"
